name: CI/CD

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.17.0
      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mini-curso-git"
          heroku_email: "jfnandopr@gmail.com"
